export const listData = [
    {
      id: 1,
      title: "Green House Apartment",
      img: "https://lh5.googleusercontent.com/p/AF1QipPp5DSdcwFw5A32FCVgD865VD4F4LBfTnVkntE=w408-h306-k-no",
      bedroom: 2,
      bathroom: 1,
      price: 1000,
      address: "ບ້ານທາດຂາວ, ເມືອງສີສັດຕະນາກ, ນະຄອນຫຼວງວຽງຈັນ",
      latitude: 17.953830,
      longitude: 102.621758,
    },
    {
      id: 2,
      title: "Vientiane Saphir Apartment",
      img: "https://lh5.googleusercontent.com/p/AF1QipMDxpo4QF4dGaanJVWAHggoazRqLPPZI3Rcyrri=w408-h544-k-no",
      bedroom: 3,
      bathroom: 2,
      price: 1500,
      address: "128 ຖະໜົນສາຍລົມ, ບ້ານສີສະຫວາດ, ເມືອງຈັນທະບູລີ, ນະຄອນຫຼວງວຽງຈັນ",
      latitude:  17.968312,
      longitude: 102.615239,
    },
    {
      id: 3,
      title: "VinJo Apartment",
      img: "https://lh5.googleusercontent.com/p/AF1QipP8uOcqOC5Zb1tIM8Ozan5-UHsI5-h-PtGfA2Op=w408-h240-k-no",
      bedroom: 1,
      bathroom: 1,
      price: 800,
      address: "ບ້ານດອນນົກຂຸ້ມ, ເມືອງສີສັດຕະນາກ, ນະຄອນຫຼວງວຽງຈັນ",
      latitude:  17.932626,
      longitude: 102.638551,
    },
    {
      id: 4,
      title: "Souphattra Serviced Apartments",
      img: "https://lh5.googleusercontent.com/p/AF1QipMs77UOaR5pYR8gbP2_5vhr1aezYgwfK0hxtEVl=w408-h272-k-no",
      bedroom: 2,
      bathroom: 1,
      price: 1000,
      address: "ບ້ານທ່າພະລານໄຊ, ເມືອງສີສັດຕະນາກ, ນະຄອນຫຼວງວຽງຈັນ",
      latitude:  17.934729,
      longitude: 102.620202,
    },
    {
      id: 5,
      title: "V Apartment",
      img: "https://lh5.googleusercontent.com/p/AF1QipM-At7nRSt4wM0O6t9TVYjLqQ3vAxkNA47eKgWQ=w408-h306-k-no",
      bedroom: 3,
      bathroom: 2,
      price: 1500,
      address: "ບ້ານສວນມອນ, ເມືອງສີສັດຕະນາກ, ນະຄອນຫຼວງວຽງຈັນ",
      latitude:  17.924175,
      longitude: 102.620439,
    },
    {
      id: 6,
      title: "KS Apartment",
      img: "https://lh5.googleusercontent.com/p/AF1QipP_nWYLPu6OnO6aafCYx78cpeGGtkuDxWUvnkJ9=w408-h306-k-no",
      bedroom: 1,
      bathroom: 1,
      price: 800,
      address: "ບ້ານສີຫອມ, ເມືອງຈັນທະບູລີ, ນະຄອນຫຼວງວຽງຈັນ",
      latitude:  17.969473,
      longitude: 102.602134,
    },
    {
      id: 7,
      title: "SP Serviced Apartments",
      img: "https://lh5.googleusercontent.com/p/AF1QipO1HNUMKEg2UWsDj_8KJAkypv0Hc3Bh60Ru7wYk=w408-h272-k-no",
      bedroom: 2,
      bathroom: 1,
      price: 1000,
      address: "ບ້ານວັດນາກ, ເມືອງສີສັດຕະນາກ, ນະຄອນຫຼວງວຽງຈັນ",
      latitude:  17.935849,
      longitude: 102.623389,
    },
    {
      id: 8,
      title: "Diamond Apartment",
      img: "https://lh5.googleusercontent.com/p/AF1QipPe-B8TyO9ngtFE2KjAMOFJpCHt-JZORG9lTE8=w408-h612-k-no",
      bedroom: 3,
      bathroom: 2,
      price: 1500,
      address: "ບ້ານສີຫອມ, ເມືອງຈັນທະບູລີ, ນະຄອນຫຼວງວຽງຈັນ",
      latitude:  17.965559,
      longitude: 102.628288,
    },
  ];
  
  export const singlePostData = {
    id: 1,
    title: "Mitsamay Apartment",
    price: 1200,
    images: [
      "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: 17.953830,
    longitude: 102.621758,
    city: "ນະຄອນຫຼວງວຽງຈັນ",
    address: "ບ້ານທາດຂາວ, ເມືອງສີສັດຕະນາກ, ນະຄອນຫຼວງວຽງຈັນ",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
  };
  
  export const userData = {
    id: 1,
    name: "John Doe",
    img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  };